name: MineReset
main: falkirks\minereset\MineReset
version: 3.2.0
author: Falk
api: [3.0.0, 4.0.0]
load: POSTWORLD
permissions:
 minereset:
  default: op
  children:
   minereset.command:
    default: op
    description:
    children:
      minereset.command.about:
        description:
      minereset.command.report:
        description:
      minereset.command.create:
        description:
      minereset.command.set:
        description:
      minereset.command.reset:
        description:
      minereset.command.destroy:
        description:
      minereset.command.resetall:
        description:
